version: '3.7'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
#    entrypoint: ["init-database.sh"]
    ports:
      - "5455:5455"
    volumes:
      - postgres_data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - "./init-database.sh:/usr/local/bin/init-database.sh"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - ${GLOBAL_NETWORK:-keycloak-network}

  keycloak-authorization-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    hostname: keycloak-server
    ports:
      - "9091:9091"
    depends_on:
      - postgres
    environment:
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin"
      - "JAVA_OPTS=-Djboss.http.port=9091"
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=postgres"
      - "DB_DATABASE=keycloak"
      - "DB_SCHEMA=public"
      - "DB_USER=keycloak"
      - "DB_PASSWORD=keycloak"
    networks:
      - ${GLOBAL_NETWORK:-keycloak-network}